### ISSUE TITLE
problem with WFA-Adapt

### ISSUE THREAD

**Issue by baoxingsong** [smarco/WFA-paper#12]
Hi, sorry. It is me again.

I am alining two sequences as attached.

And here is the score profile.

 affine_penalties_t affine_penalties = {
                .match = 0,
                .mismatch = 4,
                .gap_opening = 6,
                .gap_extension = 6,
        };

I used the cigar to reconstruct sequence alignment.

The first alignment in the attached is from the standard WFA and the second one is from your WFA-Adapt. The cigar string from the WFA-Adapt function is too long (looks like three 'M's more than expected.)

[toWFAdevelopper.txt](https://github.com/smarco/WFA/files/5461717/toWFAdevelopper.txt)

**Comment by smarco** [comment]
I close this issue as solved by previous bug fixes.
