### ISSUE TITLE
Build shared library

### ISSUE THREAD

**Issue by cschin** [smarco/WFA-paper#13]
@smarco Hi, I am adapting WFA to python through rs-wfa. For building python extension, the WFA needed to be complied to shared objects. Do you mind to change the default Makefile so it complied to shared object as well?

**Comment by smarco** [comment]
Sure, no problem. Feel free to suggest a pull request (this usually speeds up adding small changes).

Cheers,

**Comment by cschin** [comment]
@smarco thanks. just made a PR
