### ISSUE TITLE
Big gaps within alignment

### ISSUE THREAD

**Issue by lpipes** [smarco/WFA-paper#17]
Hi I am trying to align two sequences and I noticed there are some big gaps within the alignment. The gaps are usually at the very beginning or very ends of the alignment. For example:

![Screenshot from 2021-04-06 16-12-52](https://user-images.githubusercontent.com/5130783/113788929-fa44d880-96f2-11eb-9e8e-6d3dec71c5f6.png)

     affine_penalties_t affine_penalties = {
          .match = 0,
          .mismatch = 4,
          .gap_opening = 6,
          .gap_extension = 2,
      };

Is this the expected behavior? I tried setting the gap_opening penalty higher but it didn't prevent the gap.

**Comment by smarco** [comment]
Hi,

As you are executing **global** gap-affine wavefront alignment, the resulting alignment will be global or "end-to-end". Thus, the large gaps to accommodate short sequences into larger ones (like your example). Let me put it the other way round: what would be your desired result (according to your experiment or your needs)?

**Comment by lpipes** [comment]
Hi, Thanks for your quick response. When I perform a Needleman-Wunsch alignment, it produces the desired result (shown here). Is there a way to adjust the settings to create my desired alignment?
![Screenshot from 2021-04-07 04-40-57](https://user-images.githubusercontent.com/5130783/113860980-8854a980-975b-11eb-86cf-a1b366a88e32.png)

**Comment by AndreaGuarracino** [comment]
I'm also interested in managing the boundaries of alignments differently. In my case, I would probably need a semi-global alignment.

 @lpipes, which tool are you using for the NW-alignment? emboss needle? Could you please share the command line, so we can be sure of the penalties you are applying too?

**Comment by lpipes** [comment]
@AndreaGuarracino For NW, I used this code (https://github.com/noporpoise/seq-align) with the following settings:

	int match=2;
	int mismatch=-1;
	int gap_open=-3;
	int gap_extend=-1;
	int num_of_mismatches=0;
	int num_of_indels = 0;
	bool no_start_gap_penalty=true;
	bool no_end_gap_penalty=true;
	bool no_gaps_in_a = false;
	bool no_gaps_in_b = false;
	bool no_mismatches = false;
	bool case_sensitive=false;

**Comment by AndreaGuarracino** [comment]
Thank you @lpipes! Looking at your settings, it looks like you are doing a semi-global alignment, not penalizing the gaps at the start and end (`no_start_gap_penalty=true` and `no_end_gap_penalty=true`). Thanks to this relaxation, the algorithm is not "forced" to align end-to-end when dealing with sequences of different lengths. Disabling it, I would expect a similar behavior to the current wavefront alignment algorithm (WFA).

Curious to know if the WFA can easily be extended to accommodate a semi-global alignment mode.

**Comment by smarco** [comment]
Yes, as @AndreaGuarracino suggests, what you are looking for is **semi-global alignment** (a.k.a. ends-free). This will be available with the next release of the WFA (together with other additions). Many people were asking for it; so, it will be on the next release.

**Comment by lpipes** [comment]
Ok thanks for the explanation. Looking forward to it!
