### ISSUE TITLE
Performance costs of 32-bit wavefront

### ISSUE THREAD

**Issue by ekg** [smarco/WFA-paper#2]
I'm interested in applying WFA to long sequences. Is there a significant performance penalty when using the 32-bit wavefront definitions? If so, it might make sense to drive the alignment in chunks.

**Comment by smarco** [comment]
In my experience, there is no much difference. In fact, I left 32-bit wavefronts as the default and the performance results are pretty much the same (Tested on Intel HW). I left the definitions as a remainder that the algorithm can squeeze more integers in a SIMD word, gain some potential speedup, and save some memory (for very very long sequences). But in practice, this is not the bottleneck of the algorithm.

**Comment by ekg** [comment]
Do you have a paper, preprint, or presentation describing the method.

**Comment by smarco** [comment]
It is already accepted to appear on Bioinformatics (Open Access). I guess it's a matter of a few days/weeks it appears online. Not sure if at this point I can circulate a preprint (?). In any case, let me know at <santiagomsola@gmail.com>.

**Comment by 7PintsOfCherryGarcia** [comment]
Having access to the preprint would be phenomenal.

**Comment by smarco** [comment]
Here: [Fast gap-affine pairwise alignment using the wavefront algorithm, Bioinformatics](https://doi.org/10.1093/bioinformatics/btaa777)
