### ISSUE TITLE
Sample binary to report distances

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [smarco/WFA-paper#22]
It would be great if there was a provided binary that reports not only the time to align (`align_benchmark`), but also a tool that reports the actual distances.

That way, it's easier to quickly compare correctness with other aligners.

**Comment by RagnarGrootKoerkamp** [comment]
`--check` does this, although it would be better if it printed all digits without rounding, to find potential off-by-ones.

**Comment by smarco** [comment]
Hi,

The latest release, [WFA2-lib](https://github.com/smarco/WFA2-lib/), generates a short or long output with scores, CIGAR, and so. Give it a try.

Thanks for your suggestions.
