### ISSUE TITLE
Reproducing WFA results for real datasets

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [smarco/WFA-paper#26]
Hi again :)

I'd like to reuse the same real datasets you used in the paper for my benchmark.

I was wondering how exactly you go from a set of (ONP/Illumina) reads to input pairs to run WFA/global alignment on. Do you align them against the corresponding parts of a reference?

In case you used some script, it would be great if you could share it. Thanks!

**Comment by smarco** [comment]
Hi,

In the paper, we re-aligned sequences from a reference. Given any SAM file, extract the query sequence and the reference sequence. Let me look for those datasets and the script.

Cheers,

**Comment by smarco** [comment]
I've just noticed that those datasets are public on the block-aligner github:

curl -OL https://github.com/Daniel-Liu-c0deb0t/block-aligner/releases/download/v0.0.0/real.illumina.b10M.txt.gz
curl -OL https://github.com/Daniel-Liu-c0deb0t/block-aligner/releases/download/v0.0.0/real.ont.b10M.txt.gz

Cheers,
