### ISSUE TITLE
Is quadratic memory really needed

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [smarco/WFA-paper#27]
Am I right that (for small penalties) you only need to keep the front of the wavefront in memory:

Once a diagonal `k` and its two neighbouring diagonals `k-1` and `k+1` have progressed to layer at least `max(s+x, s+o+e, s+e)`, I don't think the values of `M_{0..s, k}`, `I_{0..s, k}` and `D_{0..s, k}` are needed anymore.

This could allow a reduction from `O(s^2)` memory to `O(s (o+e))` memory.

**Comment by smarco** [comment]
To be precise, if you only want to compute the alignment score/distance, you just need a "few" front wavefronts (depending on the penalties used max{open+extension,mismatch}+1). Then the memory consumption is `O(max{open+extension,mismatch})`.

However, in its basic formulation, if you want to retrieve the alignment/CIGAR, then you need to store intermediate wavefronts to be able to backtrack and reconstruct the minimum cost alignment path; i.e., `O(s^2)`

In the new release, we will offer a low-memory mode that doesn't require as much memory as the basic implementation.
