### ISSUE TITLE
compile WFA benchmark branch

### ISSUE THREAD

**Issue by Hamidreza-Ramezani** [smarco/WFA-paper#31]
Hi there, 

I'm struggling to build WFA using the Makefile provided in benchmark branch. I think the Makefile has some issues. Can you please check if you can compile it without error? resources folder cannot be linked to libwfa.so.  

Cheers,
Hamid

**Comment by Hamidreza-Ramezani** [comment]
Nevemind. I could run my experiments with master branch.

**Comment by smarco** [comment]
Hi,

Benchmark branch include other tools and libraries. In some systems, other libraries fail to compile. If you copy the error here, perhaps I can help with the error.

Bear in mind that the most updated version of WFA can be found [here](https://github.com/smarco/WFA2-lib)

This repo contains an older implementation, left for academic and research purposes as its source code is simpler to understand and modify.

**Comment by Hamidreza-Ramezani** [comment]
Many thanks for the quick reply.
