### ISSUE TITLE
change the entry's data type to int8

### ISSUE THREAD

**Issue by Hamidreza-Ramezani** [smarco/WFA-paper#32]
Hi Santiago,

I would like to use int8 instead of int32 for the entries of the DP matrix. I was wondering if you can point me to the place of the code where I can change the data type to int8? I also like to add that I found [here](https://github.com/smarco/WFA-paper/blob/master/gap_affine/affine_wavefront.h#L69-L71) where I can change the type for offsets, however, I would like to know how I can change the data type for DP matrix as well?

**Comment by smarco** [comment]
Yes, [here](https://github.com/smarco/WFA-paper/blob/master/gap_affine/affine_table.h#L42).

But remember that this repository is outdated and [WFA2-lib](https://github.com/smarco/WFA2-lib) should be used for benchmarking instead. If you let me know what you are looking for, perhaps I can help you better.

Cheers,
