### ISSUE TITLE
More usage examples

### ISSUE THREAD

**Issue by jdidion** [smarco/WFA-paper#4]
Specifically, I'm interested in the setup for global, semi-global, and local alignment modes.

**Comment by smarco** [comment]
Hi,

The current version of WFA (in accordance with the description on the Bioinformatics paper) implements "global-alignment". Nonetheless, the extension of the WFA to "ends-free", "semi-global" or similar is quite straightforward. In this sense, I am marking this as a "feature request" and I will make sure it is added on the next version.

Then, for the "global-alignment" setup I assume you had a look at the examples folder (tools/examples/*). Let me know what information/examples you need and I will try to solve any query or upload further examples.
