### ISSUE TITLE
Allocator usage recommendations

### ISSUE THREAD

**Issue by ekg** [smarco/WFA-paper#6]
If I am running alignments of many different-length alignments in a multithreaded program, what is the best way to use the memory allocator? One per thread? Is there risk of memory fragmentation or high-water bounding (memory getting stuck at the highest level during execution)?

Reading the source will answer my questions, but a high-level view of the allocator design would definitely help.

**Comment by smarco** [comment]
The mm_allocator is **not thread-safe**; that is, one mm_allocator per thread. The MemoryManaged allocator module is very simple (at the expense of potentially consuming some more memory). A list of large memory blocks ("slabs" if you want) and memory is always requested from the top (i.e., stack like). Once a slab is completely freed, it is reused. The size of the slabs is configurable (e.g., 8MB). If the request is larger than the slab's size, it is passed to malloc.
    If the allocation pattern on your application is simple enough, this module makes a large performance difference wrt to standard allocators. Note this is not a novel idea; many tools are using similar approaches.

PROS:
Lightweight allocation/deallocation calls (compared to malloc/free).
You can free the whole mm_allocator at once and save the cost of freeing each request you have made.
Transparent control over memory alignment. (*)
Some debug functions that make my life easier.

CONS:
Memory fragmentation inside the slab.
A slab cannot be freed until all requests inside it have been freed.

(*) This repo version doesn't have this feature. Once I triple-check the latest version of the mm_allocator I will push it to this repo (I'm trying to avoid introducing silly bugs; as you may have noticed...). And maybe we get some speedup out of having the memory aligned (dunno).

**Comment by baoxingsong** [comment]
how to estimate the mm_allocator usage please? for example, I want to align two sequences with 100Kbp separately. How large should I set mm_allocator as?

**Comment by smarco** [comment]
Once you allow the mm_allocator to serve memory allocating large chunks of memory (e.g., 8MB or similar) there is no significant performance difference compared to using 64MB slabs or more. The main purpose of the mm_allocator is to avoid the overheads of calling free/malloc for requesting small chunks of memory.
