### ISSUE TITLE
Possible to apply WFA in local alignment?

### ISSUE THREAD

**Issue by zhengzhenxian** [smarco/WFA-paper#8]
Thanks for your awesome work, I am interested that how to use WFA  for local alignment?  In your paper, WFA should be a global alignment algorithm, thanks!

**Comment by smarco** [comment]
Thank you for your nice words.

At this moment, the current WFA implementation only offers global-alignment. Nonetheless, we are working towards offering semi-global alignment (which is a simple extension of the current method) and exploring the viability of performing local-alignment using the WFA.

**Comment by zhengzhenxian** [comment]
That's pretty good if you are able to release a semi-global alignment version of WFA, hope to hear good news, thanks!
